
import { Inter } from "next/font/google";
import "../styles/styles.css"

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ProviderRedux from "@/redux/provider/Provider";
import ScrollToTopButton from "@/components/ScrollToTopButton/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio | Borel Anthony",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ProviderRedux>
          <Header/>
            {children}
          <Footer/>
          <ScrollToTopButton/>
        </ProviderRedux>
      </body>
    </html>
  );
}
